### ISSUE TITLE
无法复现论文中的精度指标

### ISSUE THREAD

**Issue by yangyuze1** [hanlinwu/SADN#10]
你好！再对数据集Set5，Set14，Urban100，和BSD100测试时，无法达到论文中的精度，参数配置文件和权重使用的是你公开的。请问是不是参数配置中有设置错误的？
![image](https://github.com/user-attachments/assets/91348308-b842-4d4e-81d0-7afb5ec3c0bf)

**Comment by hanlinwu** [comment]
你好，截图中展示的在自然图像数据集上的结果，为了和其他对比算法统一，这些自然图像数据集上的指标是在Y通道上计算的，即：设置test_y为True。请更改这个选项重新测试。
另外，不同计算指标的代码在结果上会有微小差异（可忽略），原文中的结果是统一使用Matlab计算的。

**Comment by hanlinwu** [comment]
另外，遥感图像的结果是使用 test_Y = False 计算的。

也欢迎关注我们的新工作，https://arxiv.org/abs/2410.22830
代码最近会上传。
祝好！

**Comment by yangyuze1** [comment]
> 你好，截图中展示的在自然图像数据集上的结果，为了和其他对比算法统一，这些自然图像数据集上的指标是在Y通道上计算的，即：设置test_y为True。请更改这个选项重新测试。 另外，不同计算指标的代码在结果上会有微小差异（可忽略），原文中的结果是统一使用Matlab计算的。

非常感谢你的帮助，目前在认真学习您的论文和代码。更改后已经达到原论文的实验精度。还有一个问题想向您请教。在测试时self_ensemble参数的作用是什么？我详细阅读了您的训练代码，发现在训练时没有用到self_ensemble，也有可能是我看的不仔细。还有根据您论文中的描述，在上采样阶段您在多个尺度图上延用了LIIF的策略，但每个尺度上只采样了图像域的一个点，您当时有尝试过完全延用LIIF的策略吗？我目前刚接触超分这个领域，对这个领域不是很了解。
![image](https://github.com/user-attachments/assets/bd0dd096-0872-4179-bfa0-3a7e8e7bc768)
