### ISSUE TITLE
Run code problem

### ISSUE THREAD

**Issue by Morayabb** [hanlinwu/SADN#4]
KeyError: "No object named 'MultiScaleSRModel' found in 'model' registry!"

Thanks for your work. There is a problem about running this code, could you please tell me how to solve it? Thank you!

**Comment by imaklex5** [comment]
+1

**Comment by hanlinwu** [comment]
Thank you for pointing out the issue. We apologize for missing a file in the previous code. The code repository has now been updated. Please try again. If there are any further issues, feel free to contact me.
