### ISSUE TITLE
div2k train

### ISSUE THREAD

**Issue by Morayabb** [hanlinwu/SADN#8]
Thank you very much for your excellent work. After configuring the environment according to readme, running the code always results in the appearance of _pickle UnpicklingError: pickle data was truncated。 Modifying seed_everything () can alleviate this issue, but it still occurs. Have you encountered it before? Is there any solution?
May I ask if there are any other configurations besides the operations mentioned in the article when training the DIV2K dataset?

**Comment by hanlinwu** [comment]
I tried running the code again, and I'm sorry I couldn't reproduce your issue, so I don't know how to resolve it. I have uploaded the pretrained weights for the DIV2K dataset and the remote sensing dataset, please see [readme.md](https://github.com/hanlinwu/SADN/blob/master/readme.md).

**Comment by Morayabb** [comment]
Thanks for your reply! But the problems I encountered before mainly came from the following reason：
![image](https://github.com/user-attachments/assets/783b9914-7843-45d5-8bfe-2a57fb01e27e)
After modifying it, there may still be problems. Do you have any good solutions? If so, please reply to me when you have time. Thank you very much!
